// autogenerated file
#![allow(unused_imports)]

pub const GAME_VERSION: &str = "1.12.2";
pub const MAJOR_GAME_VERSION: &str = "1.12";
pub const PROTOCOL_VERSION: u32 = 340;

pub mod handshaking;
pub mod login;
pub mod play;
pub mod status;
