[workspace]

members = [
    "minecraft-server-protocol", # bindings
    "minecraft-server-protocol/minecraft-server-protocol-derive", # proc macro for bindings
    "minecraft-server-protocol/generator", # generator binary, not published
]
