// autogenerated file
#![allow(unused_imports)]

pub const GAME_VERSION: &str = "1.14.3";
pub const MAJOR_GAME_VERSION: &str = "1.14";
pub const PROTOCOL_VERSION: u32 = 490;

pub mod handshaking;
pub mod status;
pub mod login;
pub mod play;
