// autogenerated file
#![allow(unused_imports)]

pub const GAME_VERSION: &str = "1.13.2";
pub const MAJOR_GAME_VERSION: &str = "1.13";
pub const PROTOCOL_VERSION: u32 = 404;

pub mod handshaking;
pub mod status;
pub mod login;
pub mod play;
