// autogenerated file
#![allow(unused_imports)]

pub const GAME_VERSION: &str = "1.15.2";
pub const MAJOR_GAME_VERSION: &str = "1.15";
pub const PROTOCOL_VERSION: u32 = 578;

pub mod handshaking;
pub mod status;
pub mod login;
pub mod play;
