// autogenerated file
#![allow(unused_imports)]

pub const GAME_VERSION: &str = "1.16-rc1";
pub const MAJOR_GAME_VERSION: &str = "1.16";
pub const PROTOCOL_VERSION: u32 = 734;

pub mod handshaking;
pub mod login;
pub mod play;
pub mod status;
