// autogenerated file
#![allow(unused_imports)]

pub const GAME_VERSION: &str = "1.13.2-pre1";
pub const MAJOR_GAME_VERSION: &str = "1.13";
pub const PROTOCOL_VERSION: u32 = 402;

pub mod handshaking;
pub mod status;
pub mod login;
pub mod play;
