// autogenerated file
#![allow(unused_imports)]

pub const GAME_VERSION: &str = "1.15.1";
pub const MAJOR_GAME_VERSION: &str = "1.15";
pub const PROTOCOL_VERSION: u32 = 575;

pub mod handshaking;
pub mod login;
pub mod play;
pub mod status;
