// autogenerated file
#![allow(unused_imports)]

pub const GAME_VERSION: &str = "21w07a";
pub const MAJOR_GAME_VERSION: &str = "1.17";
pub const PROTOCOL_VERSION: u32 = 1073741839;

pub mod handshaking;
pub mod login;
pub mod play;
pub mod status;
